cc_library(
    name = "hello-greet",
    srcs = ["hello-greet.cc"],
    copts = ['-Ilib/inc'],
    hdrs = ["inc/hello-greet.h"],
    visibility = [
        "//main:__pkg__",
        '//test:__pkg__',
    ],
)
