#!/bin/bash

script_dir=$(dirname $0)
echo script_dir ${script_dir}

export PATH=${script_dir}/bin:$PATH
export LD_LIBRARY_PATH=${script_dir}/lib:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=${script_dir}/lib:$DYLD_LIBRARY_PATH

