/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package root;

public class JnitestCJNI {
  public final static native void SomeStruct_aLong_set(long jarg1, SomeStruct jarg1_, int jarg2);
  public final static native int SomeStruct_aLong_get(long jarg1, SomeStruct jarg1_);
  public final static native void SomeStruct_aString_set(long jarg1, SomeStruct jarg1_, String jarg2);
  public final static native String SomeStruct_aString_get(long jarg1, SomeStruct jarg1_);
  public final static native void SomeStruct_aDouble_set(long jarg1, SomeStruct jarg1_, double jarg2);
  public final static native double SomeStruct_aDouble_get(long jarg1, SomeStruct jarg1_);
  public final static native long new_SomeStruct();
  public final static native void delete_SomeStruct(long jarg1);
  public final static native void StructWithArray_array_set(long jarg1, StructWithArray jarg1_, long jarg2, SomeStruct jarg2_);
  public final static native long StructWithArray_array_get(long jarg1, StructWithArray jarg1_);
  public final static native void StructWithArray_size_set(long jarg1, StructWithArray jarg1_, int jarg2);
  public final static native int StructWithArray_size_get(long jarg1, StructWithArray jarg1_);
  public final static native long new_StructWithArray();
  public final static native void delete_StructWithArray(long jarg1);
  public final static native void myfunc();
  public final static native void myfunc_name(String jarg1);
  public final static native String myfunc_name_return(String jarg1);
  public final static native void pass_array(long jarg1, int jarg2);
  public final static native void pass_array2(long jarg1, int jarg2);
  public final static native long receive_array();
  public final static native void print_array(int jarg1);
  public final static native void printSomeStruct(long jarg1, SomeStruct jarg1_);
  public final static native void printStructArray(long jarg1, int jarg2);
  public final static native void print_pointer_to_int_array(long jarg1, int jarg2);
  public final static native void printStructWithArray(long jarg1, StructWithArray jarg1_);
  public final static native void printLearnParm(long jarg1);
  public final static native void printDoc(long jarg1);
  public final static native void printWord(long jarg1);
  public final static native void printSvector(long jarg1);
  public final static native void printDocArray(long jarg1, int jarg2);
}
