/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package root;

public class StructWithArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public StructWithArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(StructWithArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JnitestCJNI.delete_StructWithArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setArray(SomeStruct value) {
    JnitestCJNI.StructWithArray_array_set(swigCPtr, this, SomeStruct.getCPtr(value), value);
  }

  public SomeStruct getArray() {
    long cPtr = JnitestCJNI.StructWithArray_array_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SomeStruct(cPtr, false);
  }

  public void setSize(int value) {
    JnitestCJNI.StructWithArray_size_set(swigCPtr, this, value);
  }

  public int getSize() {
    return JnitestCJNI.StructWithArray_size_get(swigCPtr, this);
  }

  public StructWithArray() {
    this(JnitestCJNI.new_StructWithArray(), true);
  }

}
